DROP TABLE IF EXISTS BOOK_AUTHORS;
DROP TABLE IF EXISTS BOOK_COPIES;
DROP TABLE IF EXISTS BOOK_LOANS;
DROP TABLE IF EXISTS BORROWER;
DROP TABLE IF EXISTS LIBRARY_BRANCH;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS PUBLISHER;